/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIndexRouteImport } from './routes/stories/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as VideosNewRouteImport } from './routes/videos/new'
import { Route as NewsNewRouteImport } from './routes/news/new'
import { Route as VideosIdUploadRouteImport } from './routes/videos/$id.upload'
import { Route as VideosIdTranscriptRouteImport } from './routes/videos/$id.transcript'
import { Route as VideosIdSectionsRouteImport } from './routes/videos/$id.sections'
import { Route as VideosIdLanguageTaggedRouteImport } from './routes/videos/$id.language-tagged'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosNewRoute = VideosNewRouteImport.update({
  id: '/videos/new',
  path: '/videos/new',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsNewRoute = NewsNewRouteImport.update({
  id: '/news/new',
  path: '/news/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIdUploadRoute = VideosIdUploadRouteImport.update({
  id: '/videos/$id/upload',
  path: '/videos/$id/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIdTranscriptRoute = VideosIdTranscriptRouteImport.update({
  id: '/videos/$id/transcript',
  path: '/videos/$id/transcript',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIdSectionsRoute = VideosIdSectionsRouteImport.update({
  id: '/videos/$id/sections',
  path: '/videos/$id/sections',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIdLanguageTaggedRoute = VideosIdLanguageTaggedRouteImport.update({
  id: '/videos/$id/language-tagged',
  path: '/videos/$id/language-tagged',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/news/new': typeof NewsNewRoute
  '/videos/new': typeof VideosNewRoute
  '/news/': typeof NewsIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/videos/$id/language-tagged': typeof VideosIdLanguageTaggedRoute
  '/videos/$id/sections': typeof VideosIdSectionsRoute
  '/videos/$id/transcript': typeof VideosIdTranscriptRoute
  '/videos/$id/upload': typeof VideosIdUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/news/new': typeof NewsNewRoute
  '/videos/new': typeof VideosNewRoute
  '/news': typeof NewsIndexRoute
  '/stories': typeof StoriesIndexRoute
  '/videos/$id/language-tagged': typeof VideosIdLanguageTaggedRoute
  '/videos/$id/sections': typeof VideosIdSectionsRoute
  '/videos/$id/transcript': typeof VideosIdTranscriptRoute
  '/videos/$id/upload': typeof VideosIdUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/news/new': typeof NewsNewRoute
  '/videos/new': typeof VideosNewRoute
  '/news/': typeof NewsIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/videos/$id/language-tagged': typeof VideosIdLanguageTaggedRoute
  '/videos/$id/sections': typeof VideosIdSectionsRoute
  '/videos/$id/transcript': typeof VideosIdTranscriptRoute
  '/videos/$id/upload': typeof VideosIdUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/news/new'
    | '/videos/new'
    | '/news/'
    | '/stories/'
    | '/videos/$id/language-tagged'
    | '/videos/$id/sections'
    | '/videos/$id/transcript'
    | '/videos/$id/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/news/new'
    | '/videos/new'
    | '/news'
    | '/stories'
    | '/videos/$id/language-tagged'
    | '/videos/$id/sections'
    | '/videos/$id/transcript'
    | '/videos/$id/upload'
  id:
    | '__root__'
    | '/'
    | '/news/new'
    | '/videos/new'
    | '/news/'
    | '/stories/'
    | '/videos/$id/language-tagged'
    | '/videos/$id/sections'
    | '/videos/$id/transcript'
    | '/videos/$id/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewsNewRoute: typeof NewsNewRoute
  VideosNewRoute: typeof VideosNewRoute
  NewsIndexRoute: typeof NewsIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
  VideosIdLanguageTaggedRoute: typeof VideosIdLanguageTaggedRoute
  VideosIdSectionsRoute: typeof VideosIdSectionsRoute
  VideosIdTranscriptRoute: typeof VideosIdTranscriptRoute
  VideosIdUploadRoute: typeof VideosIdUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/new': {
      id: '/videos/new'
      path: '/videos/new'
      fullPath: '/videos/new'
      preLoaderRoute: typeof VideosNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/new': {
      id: '/news/new'
      path: '/news/new'
      fullPath: '/news/new'
      preLoaderRoute: typeof NewsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$id/upload': {
      id: '/videos/$id/upload'
      path: '/videos/$id/upload'
      fullPath: '/videos/$id/upload'
      preLoaderRoute: typeof VideosIdUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$id/transcript': {
      id: '/videos/$id/transcript'
      path: '/videos/$id/transcript'
      fullPath: '/videos/$id/transcript'
      preLoaderRoute: typeof VideosIdTranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$id/sections': {
      id: '/videos/$id/sections'
      path: '/videos/$id/sections'
      fullPath: '/videos/$id/sections'
      preLoaderRoute: typeof VideosIdSectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$id/language-tagged': {
      id: '/videos/$id/language-tagged'
      path: '/videos/$id/language-tagged'
      fullPath: '/videos/$id/language-tagged'
      preLoaderRoute: typeof VideosIdLanguageTaggedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewsNewRoute: NewsNewRoute,
  VideosNewRoute: VideosNewRoute,
  NewsIndexRoute: NewsIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
  VideosIdLanguageTaggedRoute: VideosIdLanguageTaggedRoute,
  VideosIdSectionsRoute: VideosIdSectionsRoute,
  VideosIdTranscriptRoute: VideosIdTranscriptRoute,
  VideosIdUploadRoute: VideosIdUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
